name: Go Code Checks

on:
  push:
    branches: [main]
    paths:
      - "code/**"
  pull_request:
    paths:
      - "code/**"
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        project: [project-1-blog, project-2-marketplace, project-3-youtube-clone]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/${{ matrix.project }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...
